
;;
;; DO NOT EDIT THIS FILE BY HAND!
;; This file is generated from thomasf-emacs.org
;;

(provide 'thomasf-init)

(if (fboundp 'menu-bar-mode) (menu-bar-mode -1))
(if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))

(setq inhibit-startup-message t
      inhibit-splash-screen t
      inhibit-startup-buffer-menu t
      inhibit-startup-echo-area-message t
      initial-scratch-message ";; scratch buffer -- remember to be happy, maybe, etc. \n\n")

(when (or (not (boundp 'emacs-version))
          (string< emacs-version "24.0"))
  (error (concat "emacs config requires Emacs 24.0 or later.")))

(setq vendor-dir (concat dotfiles-dir "vendor/"))
(setq notes-dir (file-truename "~/notes/"))

(let ((default-directory vendor-dir))
  (setq load-path
        (append
         (let ((load-path (copy-sequence load-path)))
           (append
            (copy-sequence (normal-top-level-add-to-load-path '(".")))
            (normal-top-level-add-subdirs-to-load-path)))
         load-path)))
(setq org-modules '(org-bibtex org-docview org-id org-info org-jsinfo org-habit org-mew org-mhe org-vm org-wl org-w3m org-git-link org-velocity))
(require 'cl)
(require 'org-install)
