
;;
;; DO NOT EDIT THIS FILE BY HAND!
;; This file is generated from thomasf-emacs.org
;;

(setq load-path (cons (concat dotfiles-dir "vendor/org-mode/lisp") load-path))
(setq load-path (cons (concat dotfiles-dir "vendor/org-mode/contrib/lisp") load-path))
(setq org-modules '(org-bibtex org-docview org-id org-info org-jsinfo org-habit org-mew org-mhe org-vm org-wl org-w3m org-git-link org-velocity))
(require 'org-install)
(provide 'thomasf-init)
